name: beerstory
description: Save your favorite beers and find them back instantly !
version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  hive: ^1.1.1
  hive_flutter: ^0.2.1
  http: ^0.12.0
  image_picker: ^0.6.1
  intl: ^0.16.0
  path_provider: ^1.4.0
  flutter_svg: ^0.14.4
  smooth_star_rating: ^1.0.3
  url_launcher: ^5.2.5
  flutter_barcode_scanner: ^0.1.7
  ez_localization: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: ^0.5.2
  build_runner: ^1.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/languages/
  fonts:
    - family: BirdsOfParadise
      fonts:
        - asset: assets/fonts/BirdsOfParadise.ttf
